export const data = [
  {
    employer_name: 'confidential',
    employer_logo: null,
    employer_website: null,
    employer_company_type: null,
    job_publisher: 'Apex Systems',
    job_id: 'txphdIGdkVYAAAAAAAAAAA==',
    job_employment_type: 'CONTRACTOR',
    job_title: 'React Developer',
    job_apply_link: 'https://www.apexsystems.com/job/1346691_usa/react-developer',
    job_apply_is_direct: false,
    job_apply_quality_score: 0.779,
    job_description:
      'Apex Systems is looking for a React Developer to join a Fortune 100 team. Please submit your resume if you are interested in applying.\n\nRequired Experience:\n\n- 6+ years as a React Developer\n\n- Have experience with React JS, CSS, HTML and Cloud\n\n- Be able to go onsite as needed in Bentonville, AR or relocate to Bentonville\n\n- Experience working from scratch\n\nEEO EmployerApex Systems is an equal opportunity employer. We do not discriminate or allow discrimination on the basis of race, color, religion, creed, sex (including pregnancy, childbirth, breastfeeding, or related medical conditions), age, sexual orientation, gender identity, national origin, ancestry, citizenship, genetic information, registered domestic partner status, marital status, disability, status as a crime victim, protected veteran status, political affiliation, union membership, or any other characteristic protected by law. Apex will consider qualified applicants with criminal histories in a manner consistent with the requirements of applicable law. If you have visited our website in search of information on employment opportunities or to apply for a position, and you require an accommodation in using our website for a search or application, please contact our Employee Services Department at employeeservices@apexsystems.com or 844-463-6178.',
    job_is_remote: false,
    job_posted_at_timestamp: 1683590400,
    job_posted_at_datetime_utc: '2023-05-09T00:00:00.000Z',
    job_city: 'Bentonville',
    job_state: 'AR',
    job_country: 'US',
    job_latitude: 36.372356,
    job_longitude: -94.21021,
    job_benefits: null,
    job_google_link:
      'https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=txphdIGdkVYAAAAAAAAAAA%3D%3D',
    job_offer_expiration_datetime_utc: null,
    job_offer_expiration_timestamp: null,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: null,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        '6+ years as a React Developer',
        'Have experience with React JS, CSS, HTML and Cloud',
        'Be able to go onsite as needed in Bentonville, AR or relocate to Bentonville',
        'Experience working from scratch',
      ],
    },
    job_job_title: null,
    job_posting_language: 'en',
    job_onet_soc: '15113400',
    job_onet_job_zone: '3',
  },
  {
    employer_name: 'Upwork',
    employer_logo: 'https://image.status.io/z6aeO6kAGsAG.png',
    employer_website: 'http://www.elance.com',
    employer_company_type: 'Computer Services',
    job_publisher: 'Upwork',
    job_id: 'vnYv3I_SZBsAAAAAAAAAAA==',
    job_employment_type: 'CONTRACTOR',
    job_title: 'ReactJS developer needed',
    job_apply_link: 'https://www.upwork.com/freelance-jobs/apply/ReactJS-developer-needed_~01dfa41d02e3ef1e75/',
    job_apply_is_direct: true,
    job_apply_quality_score: 0.6821,
    job_description:
      'Require a React developer to build a dynamic website which must be mobile friendly. Tasks will include:\n\nAuthentication + using social media connect, Session management, Custom tables and dynamic layouts for case management, Custom reports with graphs. Media gallery, Writing custom JS for many UI requirements, API connectivity, etc.\n\nSend experience and sample work (live URLs) where you used React only. Also mention minimum weekly hour availability and hourly rate. Selected candidates will undergo a call screen.',
    job_is_remote: true,
    job_posted_at_timestamp: 1687288303,
    job_posted_at_datetime_utc: '2023-06-20T19:11:43.000Z',
    job_city: null,
    job_state: null,
    job_country: 'US',
    job_latitude: 37.09024,
    job_longitude: -95.71289,
    job_benefits: null,
    job_google_link:
      'https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=vnYv3I_SZBsAAAAAAAAAAA%3D%3D',
    job_offer_expiration_datetime_utc: null,
    job_offer_expiration_timestamp: null,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: null,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: ['React'],
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: 8,
    job_max_salary: 14,
    job_salary_currency: 'USD',
    job_salary_period: 'HOUR',
    job_highlights: {
      Responsibilities: [
        'Authentication + using social media connect, Session management, Custom tables and dynamic layouts for case management, Custom reports with graphs',
        'Media gallery, Writing custom JS for many UI requirements, API connectivity, etc',
      ],
    },
    job_job_title: null,
    job_posting_language: 'en',
    job_onet_soc: '15113400',
    job_onet_job_zone: '3',
    job_naics_code: '541511',
    job_naics_name: 'Custom Computer Programming Services',
  },
  {
    employer_name: 'Clevertech',
    employer_logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcREroK3iLsY8CwCfpKcCn3hQdZy5Zf_6RvqAoDl&s=0',
    employer_website: null,
    employer_company_type: null,
    job_publisher: 'LinkedIn',
    job_id: 'iCdrcCJfVxUAAAAAAAAAAA==',
    job_employment_type: 'FULLTIME',
    job_title: 'Node + React Developer',
    job_apply_link: 'https://www.linkedin.com/jobs/view/node-%2B-react-developer-at-clevertech-3640108304',
    job_apply_is_direct: false,
    job_apply_quality_score: 0.5841,
    job_description:
      "Experience Remote done Right.\n\nOver 20 years of remote experience, all 500+ staff are 100% remote and we still grow vibrant relationships, provide exceptional opportunities for career growth while working with stellar clients on ambitious projects\n\nWhat we're working on:\n\nEnterprise companies turn to us to help them launch innovative digital products that interact with hundreds of millions of customers, transactions and data points. The problems we solve every day are real and require creativity, grit and determination. We are building a culture that challenges norms while fostering experimentation and personal growth. In order to grasp the scale of problems we face, ideally, you have some exposure to Logistics, FinTech, Transportation, Insurance, Media or other complex multifactor industries\n\nRequirements\n• 7+ years of professional experience (A technical assessment will be required)\n• Senior-level experience in the front-end (React) and back-end (Node, Express, Mongo, SQL)\n• Ability to create clean, modern, testable, well-documented code\n• English fluency, verbal and written\n• Professional, empathic, team player\n• Problem solver, proactive, go-getter\n\nWhy Clevertech is an amazing place to work at\n\nAt Clevertech, you can expect that you will:\n• Be 100% dedicated to one project at a time so that you can hone your skills, innovate and grow\n• Be a part of a team of talented and friendly senior-level developers\n• Work on projects that allow you to use cutting edge tech. We believe in constantly evolving your mastery\n\nThe result? We produce meaningful work and we are truly proud and excited to be creating waves in an industry under transformation.\n\nBenefits of joining the Clevertech team:\n• Competitive Salaries\n• 1 Month Paid Time Off For You\n• Personal Development Fund\n• Tenure-Based Rewards\n• Flexible Family Leave\n• Clevertech University\n• Clevertech Gives Back\n• Amazing Culture & Strong Community",
    job_is_remote: true,
    job_posted_at_timestamp: 1687199775,
    job_posted_at_datetime_utc: '2023-06-19T18:36:15.000Z',
    job_city: null,
    job_state: null,
    job_country: 'US',
    job_latitude: 37.09024,
    job_longitude: -95.71289,
    job_benefits: ['paid_time_off'],
    job_google_link:
      'https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=iCdrcCJfVxUAAAAAAAAAAA%3D%3D',
    job_offer_expiration_datetime_utc: '2023-07-19T18:36:15.000Z',
    job_offer_expiration_timestamp: 1689791775,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: 240,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: true,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        '7+ years of professional experience (A technical assessment will be required)',
        'Senior-level experience in the front-end (React) and back-end (Node, Express, Mongo, SQL)',
        'Ability to create clean, modern, testable, well-documented code',
        'English fluency, verbal and written',
        'Professional, empathic, team player',
        'Problem solver, proactive, go-getter',
      ],
      Responsibilities: [
        'In order to grasp the scale of problems we face, ideally, you have some exposure to Logistics, FinTech, Transportation, Insurance, Media or other complex multifactor industries',
      ],
      Benefits: [
        'Competitive Salaries',
        '1 Month Paid Time Off For You',
        'Personal Development Fund',
        'Tenure-Based Rewards',
        'Flexible Family Leave',
        'Clevertech University',
        'Amazing Culture & Strong Community',
      ],
    },
    job_job_title: null,
    job_posting_language: 'en',
    job_onet_soc: '15113400',
    job_onet_job_zone: '3',
  },
  {
    employer_name: 'Upwork',
    employer_logo: 'https://image.status.io/z6aeO6kAGsAG.png',
    employer_website: 'http://www.elance.com',
    employer_company_type: 'Computer Services',
    job_publisher: 'Upwork',
    job_id: 'CLMg6Qh9qbYAAAAAAAAAAA==',
    job_employment_type: 'CONTRACTOR',
    job_title: 'React Developer',
    job_apply_link: 'https://www.upwork.com/freelance-jobs/apply/React-Developer_~01e2d600e181f6ab02/',
    job_apply_is_direct: true,
    job_apply_quality_score: 0.6821,
    job_description:
      "Looking for a talented Frontend Developer to join a dynamic team on a new project - a Book List app with exciting features. You'll develop user-facing features using React.js, build reusable components, and translate designs into high-quality code. Need 2+ years of frontend experience, proficiency in JavaScript (ES6), HTML5, CSS3, React.js, and familiarity with RESTful APIs. Experience with Babel, Webpack, and Git preferred.",
    job_is_remote: true,
    job_posted_at_timestamp: 1687283303,
    job_posted_at_datetime_utc: '2023-06-20T17:48:23.000Z',
    job_city: null,
    job_state: null,
    job_country: 'US',
    job_latitude: 37.09024,
    job_longitude: -95.71289,
    job_benefits: null,
    job_google_link:
      'https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=CLMg6Qh9qbYAAAAAAAAAAA%3D%3D',
    job_offer_expiration_datetime_utc: null,
    job_offer_expiration_timestamp: null,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: 24,
      experience_mentioned: true,
      experience_preferred: true,
    },
    job_required_skills: [
      'React',
      'JavaScript',
      'Front-End Development',
      'Recruiting',
      'Candidate Recommendation',
      'Candidate Interviewing',
      'Java',
      'CSS',
      'HTML',
      'HTML5',
    ],
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        'Need 2+ years of frontend experience, proficiency in JavaScript (ES6), HTML5, CSS3, React.js, and familiarity with RESTful APIs',
      ],
      Responsibilities: [
        "You'll develop user-facing features using React.js, build reusable components, and translate designs into high-quality code",
      ],
    },
    job_job_title: null,
    job_posting_language: 'en',
    job_onet_soc: '15113400',
    job_onet_job_zone: '3',
    job_naics_code: '541511',
    job_naics_name: 'Custom Computer Programming Services',
  },
]
